/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@revolist/revogrid';


interface RevogrEditProps {
  
  /**  */
  editCell?: Components.RevogrEdit["editCell"]
  
  /**  */
  column?: Components.RevogrEdit["column"]
  
  /** Custom editors register */
  editor?: Components.RevogrEdit["editor"]
}

interface RevogrEditEvents {
  
  /**  */
  cellEdit: Parameters<JSX.RevogrEdit["onCellEdit"]>[0]
  
  /** Close editor event */
  closeEdit: Parameters<JSX.RevogrEdit["onCloseEdit"]>[0]
}

interface RevogrEditSlots {
  default: any
}
  
/* generated by Svelte v3.49.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	listen,
	run_all,
	safe_not_equal,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let revogr_edit;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[8].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[7], null);

	return {
		c() {
			revogr_edit = element("revogr-edit");
			if (default_slot) default_slot.c();
		},
		m(target, anchor) {
			insert(target, revogr_edit, anchor);

			if (default_slot) {
				default_slot.m(revogr_edit, null);
			}

			/*revogr_edit_binding*/ ctx[9](revogr_edit);
			current = true;

			if (!mounted) {
				dispose = [
					listen(revogr_edit, "cellEdit", /*onEvent*/ ctx[1]),
					listen(revogr_edit, "closeEdit", /*onEvent*/ ctx[1])
				];

				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 128)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[7],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[7])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[7], dirty, null),
						null
					);
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(revogr_edit);
			if (default_slot) default_slot.d(detaching);
			/*revogr_edit_binding*/ ctx[9](null);
			mounted = false;
			run_all(dispose);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { editCell = undefined } = $$props;
	let { column = undefined } = $$props;
	let { editor = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(6, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(0, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function revogr_edit_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(0, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('editCell' in $$props) $$invalidate(2, editCell = $$props.editCell);
		if ('column' in $$props) $$invalidate(3, column = $$props.column);
		if ('editor' in $$props) $$invalidate(4, editor = $$props.editor);
		if ('$$scope' in $$props) $$invalidate(7, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, editCell*/ 68) {
			$: if (__mounted) setProp('editCell', editCell);
		}

		if ($$self.$$.dirty & /*__mounted, column*/ 72) {
			$: if (__mounted) setProp('column', column);
		}

		if ($$self.$$.dirty & /*__mounted, editor*/ 80) {
			$: if (__mounted) setProp('editor', editor);
		}
	};

	return [
		__ref,
		onEvent,
		editCell,
		column,
		editor,
		getWebComponent,
		__mounted,
		$$scope,
		slots,
		revogr_edit_binding
	];
}

class RevogrEdit extends SvelteComponent {
  $$prop_def: RevogrEditProps;
  $$events_def: RevogrEditEvents;
  $$slot_def: RevogrEditSlots;

  $on<K extends keyof RevogrEditEvents>(type: K, callback: (e: RevogrEditEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<RevogrEditProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			editCell: 2,
			column: 3,
			editor: 4,
			getWebComponent: 5
		});
	}

	get getWebComponent(): HTMLRevogrEditElement | undefined {
		return this.$$.ctx[5];
	}
}

export default RevogrEdit;