/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@revolist/revogrid';


interface RevogrFocusProps {
  
  /** Dynamic stores */
  dataStore?: Components.RevogrFocus["dataStore"]
  
  /**  */
  colData?: Components.RevogrFocus["colData"]
  
  /**  */
  selectionStore?: Components.RevogrFocus["selectionStore"]
  
  /**  */
  dimensionRow?: Components.RevogrFocus["dimensionRow"]
  
  /**  */
  dimensionCol?: Components.RevogrFocus["dimensionCol"]
}

interface RevogrFocusEvents {
  
  /**  */
  afterfocus: Parameters<JSX.RevogrFocus["onAfterfocus"]>[0]
}

interface RevogrFocusSlots {
  default: any
}
  
/* generated by Svelte v3.49.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	listen,
	safe_not_equal,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let revogr_focus;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[10].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[9], null);

	return {
		c() {
			revogr_focus = element("revogr-focus");
			if (default_slot) default_slot.c();
		},
		m(target, anchor) {
			insert(target, revogr_focus, anchor);

			if (default_slot) {
				default_slot.m(revogr_focus, null);
			}

			/*revogr_focus_binding*/ ctx[11](revogr_focus);
			current = true;

			if (!mounted) {
				dispose = listen(revogr_focus, "afterfocus", /*onEvent*/ ctx[1]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 512)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[9],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[9])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[9], dirty, null),
						null
					);
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(revogr_focus);
			if (default_slot) default_slot.d(detaching);
			/*revogr_focus_binding*/ ctx[11](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { dataStore } = $$props;
	let { colData } = $$props;
	let { selectionStore } = $$props;
	let { dimensionRow } = $$props;
	let { dimensionCol } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(8, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(0, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function revogr_focus_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(0, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('dataStore' in $$props) $$invalidate(2, dataStore = $$props.dataStore);
		if ('colData' in $$props) $$invalidate(3, colData = $$props.colData);
		if ('selectionStore' in $$props) $$invalidate(4, selectionStore = $$props.selectionStore);
		if ('dimensionRow' in $$props) $$invalidate(5, dimensionRow = $$props.dimensionRow);
		if ('dimensionCol' in $$props) $$invalidate(6, dimensionCol = $$props.dimensionCol);
		if ('$$scope' in $$props) $$invalidate(9, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, dataStore*/ 260) {
			$: if (__mounted) setProp('dataStore', dataStore);
		}

		if ($$self.$$.dirty & /*__mounted, colData*/ 264) {
			$: if (__mounted) setProp('colData', colData);
		}

		if ($$self.$$.dirty & /*__mounted, selectionStore*/ 272) {
			$: if (__mounted) setProp('selectionStore', selectionStore);
		}

		if ($$self.$$.dirty & /*__mounted, dimensionRow*/ 288) {
			$: if (__mounted) setProp('dimensionRow', dimensionRow);
		}

		if ($$self.$$.dirty & /*__mounted, dimensionCol*/ 320) {
			$: if (__mounted) setProp('dimensionCol', dimensionCol);
		}
	};

	return [
		__ref,
		onEvent,
		dataStore,
		colData,
		selectionStore,
		dimensionRow,
		dimensionCol,
		getWebComponent,
		__mounted,
		$$scope,
		slots,
		revogr_focus_binding
	];
}

class RevogrFocus extends SvelteComponent {
  $$prop_def: RevogrFocusProps;
  $$events_def: RevogrFocusEvents;
  $$slot_def: RevogrFocusSlots;

  $on<K extends keyof RevogrFocusEvents>(type: K, callback: (e: RevogrFocusEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<RevogrFocusProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			dataStore: 2,
			colData: 3,
			selectionStore: 4,
			dimensionRow: 5,
			dimensionCol: 6,
			getWebComponent: 7
		});
	}

	get getWebComponent(): HTMLRevogrFocusElement | undefined {
		return this.$$.ctx[7];
	}
}

export default RevogrFocus;