/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@revolist/revogrid';


interface RevogrClipboardProps {
  
}

interface RevogrClipboardEvents {
  
  /**  */
  copyRegion: Parameters<JSX.RevogrClipboard["onCopyRegion"]>[0]
  
  /**  */
  pasteRegion: Parameters<JSX.RevogrClipboard["onPasteRegion"]>[0]
}

interface RevogrClipboardSlots {
  default: any
}
  
/* generated by Svelte v3.49.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	listen,
	run_all,
	safe_not_equal,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let revogr_clipboard;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[5].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[4], null);

	return {
		c() {
			revogr_clipboard = element("revogr-clipboard");
			if (default_slot) default_slot.c();
		},
		m(target, anchor) {
			insert(target, revogr_clipboard, anchor);

			if (default_slot) {
				default_slot.m(revogr_clipboard, null);
			}

			/*revogr_clipboard_binding*/ ctx[6](revogr_clipboard);
			current = true;

			if (!mounted) {
				dispose = [
					listen(revogr_clipboard, "copyRegion", /*onEvent*/ ctx[1]),
					listen(revogr_clipboard, "pasteRegion", /*onEvent*/ ctx[1])
				];

				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 16)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[4],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[4])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[4], dirty, null),
						null
					);
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(revogr_clipboard);
			if (default_slot) default_slot.d(detaching);
			/*revogr_clipboard_binding*/ ctx[6](null);
			mounted = false;
			run_all(dispose);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	const doCopy = (...args) => __ref.doCopy(...args);
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(0, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function revogr_clipboard_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(0, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('$$scope' in $$props) $$invalidate(4, $$scope = $$props.$$scope);
	};

	return [
		__ref,
		onEvent,
		doCopy,
		getWebComponent,
		$$scope,
		slots,
		revogr_clipboard_binding
	];
}

class RevogrClipboard extends SvelteComponent {
  $$prop_def: RevogrClipboardProps;
  $$events_def: RevogrClipboardEvents;
  $$slot_def: RevogrClipboardSlots;

  $on<K extends keyof RevogrClipboardEvents>(type: K, callback: (e: RevogrClipboardEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<RevogrClipboardProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { doCopy: 2, getWebComponent: 3 });
	}

	
  /**  */
 get doCopy(): Components.RevogrClipboard["doCopy"] {
		return this.$$.ctx[2];
	}

	get getWebComponent(): HTMLRevogrClipboardElement | undefined {
		return this.$$.ctx[3];
	}
}

export default RevogrClipboard;