/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { Components, JSX } from '@revolist/revogrid';


interface RevogrTempRangeProps {
  
  /** Selection store, shows current selection and focus */
  selectionStore?: Components.RevogrTempRange["selectionStore"]
  
  /** Dimension row store */
  dimensionRow?: Components.RevogrTempRange["dimensionRow"]
  
  /** Dimension column store */
  dimensionCol?: Components.RevogrTempRange["dimensionCol"]
}

interface RevogrTempRangeEvents {
  
}

interface RevogrTempRangeSlots {
  default: any
}
  
/* generated by Svelte v4.2.15 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	safe_not_equal,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import "svelte/internal/disclose-version";
import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let revogr_temp_range;
	let current;
	const default_slot_template = /*#slots*/ ctx[7].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[6], null);

	return {
		c() {
			revogr_temp_range = element("revogr-temp-range");
			if (default_slot) default_slot.c();
		},
		m(target, anchor) {
			insert(target, revogr_temp_range, anchor);

			if (default_slot) {
				default_slot.m(revogr_temp_range, null);
			}

			/*revogr_temp_range_binding*/ ctx[8](revogr_temp_range);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 64)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[6],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[6])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[6], dirty, null),
						null
					);
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) {
				detach(revogr_temp_range);
			}

			if (default_slot) default_slot.d(detaching);
			/*revogr_temp_range_binding*/ ctx[8](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { selectionStore = undefined } = $$props;
	let { dimensionRow = undefined } = $$props;
	let { dimensionCol = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(5, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(0, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function revogr_temp_range_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(0, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('selectionStore' in $$props) $$invalidate(1, selectionStore = $$props.selectionStore);
		if ('dimensionRow' in $$props) $$invalidate(2, dimensionRow = $$props.dimensionRow);
		if ('dimensionCol' in $$props) $$invalidate(3, dimensionCol = $$props.dimensionCol);
		if ('$$scope' in $$props) $$invalidate(6, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, selectionStore*/ 34) {
			$: if (__mounted) setProp('selectionStore', selectionStore);
		}

		if ($$self.$$.dirty & /*__mounted, dimensionRow*/ 36) {
			$: if (__mounted) setProp('dimensionRow', dimensionRow);
		}

		if ($$self.$$.dirty & /*__mounted, dimensionCol*/ 40) {
			$: if (__mounted) setProp('dimensionCol', dimensionCol);
		}
	};

	return [
		__ref,
		selectionStore,
		dimensionRow,
		dimensionCol,
		getWebComponent,
		__mounted,
		$$scope,
		slots,
		revogr_temp_range_binding
	];
}

class RevogrTempRange extends SvelteComponent {
  $$prop_def: RevogrTempRangeProps;
  $$events_def: RevogrTempRangeEvents;
  $$slot_def: RevogrTempRangeSlots;

  $on<K extends keyof RevogrTempRangeEvents>(type: K, callback: (e: RevogrTempRangeEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<RevogrTempRangeProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			selectionStore: 1,
			dimensionRow: 2,
			dimensionCol: 3,
			getWebComponent: 4
		});
	}

	get getWebComponent(): HTMLRevogrTempRangeElement | undefined {
		return this.$$.ctx[4];
	}
}

export default RevogrTempRange;