/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@revolist/revogrid';


interface RevogrDataProps {
  
  /** Readonly mode */
  readonly?: Components.RevogrData["readonly"]
  
  /** Range allowed */
  range?: Components.RevogrData["range"]
  
  /** Defines property from which to read row class */
  rowClass?: Components.RevogrData["rowClass"]
  
  /** Additional data to pass to renderer
Used in plugins such as vue or react to pass root app entity to cells */
  additionalData?: Components.RevogrData["additionalData"]
  
  /** Selection, range, focus for row selection */
  rowSelectionStore?: Components.RevogrData["rowSelectionStore"]
  
  /** Viewport Y */
  viewportRow?: Components.RevogrData["viewportRow"]
  
  /** Viewport X */
  viewportCol?: Components.RevogrData["viewportCol"]
  
  /** Dimension settings Y */
  dimensionRow?: Components.RevogrData["dimensionRow"]
  
  /** Column source */
  colData?: Components.RevogrData["colData"]
  
  /** Data rows source */
  dataStore?: Components.RevogrData["dataStore"]
  
  /** Row data type */
  type?: Components.RevogrData["type"]
  
  /** Column data type */
  colType?: Components.RevogrData["colType"]
  
  /** Prevent rendering until job is done.
Can be used for initial rendering performance improvement.
When several plugins require initial rendering this will prevent double initial rendering. */
  jobsBeforeRender?: Components.RevogrData["jobsBeforeRender"]
}

interface RevogrDataEvents {
  
  /** Before each row render */
  beforerowrender: Parameters<JSX.RevogrData["onBeforerowrender"]>[0]
  
  /** When data render finished for the designated type */
  afterrender: Parameters<JSX.RevogrData["onAfterrender"]>[0]
  
  /** Before each cell render function. Allows to override cell properties */
  beforecellrender: Parameters<JSX.RevogrData["onBeforecellrender"]>[0]
  
  /** Event emitted on cell drag start */
  dragstartcell: Parameters<JSX.RevogrData["onDragstartcell"]>[0]
}

interface RevogrDataSlots {
  default: any
}
  
/* generated by Svelte v4.2.15 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	listen,
	run_all,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import "svelte/internal/disclose-version";
import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let revogr_data;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[19].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[18], null);

	return {
		c() {
			revogr_data = element("revogr-data");
			if (default_slot) default_slot.c();
			set_custom_element_data(revogr_data, "readonly", /*readonly*/ ctx[0]);
			set_custom_element_data(revogr_data, "range", /*range*/ ctx[1]);
			set_custom_element_data(revogr_data, "row-class", /*rowClass*/ ctx[2]);
			set_custom_element_data(revogr_data, "additional-data", /*additionalData*/ ctx[3]);
			set_custom_element_data(revogr_data, "type", /*type*/ ctx[4]);
			set_custom_element_data(revogr_data, "col-type", /*colType*/ ctx[5]);
		},
		m(target, anchor) {
			insert(target, revogr_data, anchor);

			if (default_slot) {
				default_slot.m(revogr_data, null);
			}

			/*revogr_data_binding*/ ctx[20](revogr_data);
			current = true;

			if (!mounted) {
				dispose = [
					listen(revogr_data, "beforerowrender", /*onEvent*/ ctx[7]),
					listen(revogr_data, "afterrender", /*onEvent*/ ctx[7]),
					listen(revogr_data, "beforecellrender", /*onEvent*/ ctx[7]),
					listen(revogr_data, "dragstartcell", /*onEvent*/ ctx[7])
				];

				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 262144)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[18],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[18])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[18], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*readonly*/ 1) {
				set_custom_element_data(revogr_data, "readonly", /*readonly*/ ctx[0]);
			}

			if (!current || dirty & /*range*/ 2) {
				set_custom_element_data(revogr_data, "range", /*range*/ ctx[1]);
			}

			if (!current || dirty & /*rowClass*/ 4) {
				set_custom_element_data(revogr_data, "row-class", /*rowClass*/ ctx[2]);
			}

			if (!current || dirty & /*additionalData*/ 8) {
				set_custom_element_data(revogr_data, "additional-data", /*additionalData*/ ctx[3]);
			}

			if (!current || dirty & /*type*/ 16) {
				set_custom_element_data(revogr_data, "type", /*type*/ ctx[4]);
			}

			if (!current || dirty & /*colType*/ 32) {
				set_custom_element_data(revogr_data, "col-type", /*colType*/ ctx[5]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) {
				detach(revogr_data);
			}

			if (default_slot) default_slot.d(detaching);
			/*revogr_data_binding*/ ctx[20](null);
			mounted = false;
			run_all(dispose);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { readonly = undefined } = $$props;
	let { range = undefined } = $$props;
	let { rowClass = undefined } = $$props;
	let { additionalData = undefined } = $$props;
	let { rowSelectionStore } = $$props;
	let { viewportRow } = $$props;
	let { viewportCol } = $$props;
	let { dimensionRow } = $$props;
	let { colData = undefined } = $$props;
	let { dataStore } = $$props;
	let { type } = $$props;
	let { colType } = $$props;
	let { jobsBeforeRender = undefined } = $$props;
	const updateCell = (...args) => __ref.updateCell(...args);
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(17, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(6, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function revogr_data_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(6, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('readonly' in $$props) $$invalidate(0, readonly = $$props.readonly);
		if ('range' in $$props) $$invalidate(1, range = $$props.range);
		if ('rowClass' in $$props) $$invalidate(2, rowClass = $$props.rowClass);
		if ('additionalData' in $$props) $$invalidate(3, additionalData = $$props.additionalData);
		if ('rowSelectionStore' in $$props) $$invalidate(8, rowSelectionStore = $$props.rowSelectionStore);
		if ('viewportRow' in $$props) $$invalidate(9, viewportRow = $$props.viewportRow);
		if ('viewportCol' in $$props) $$invalidate(10, viewportCol = $$props.viewportCol);
		if ('dimensionRow' in $$props) $$invalidate(11, dimensionRow = $$props.dimensionRow);
		if ('colData' in $$props) $$invalidate(12, colData = $$props.colData);
		if ('dataStore' in $$props) $$invalidate(13, dataStore = $$props.dataStore);
		if ('type' in $$props) $$invalidate(4, type = $$props.type);
		if ('colType' in $$props) $$invalidate(5, colType = $$props.colType);
		if ('jobsBeforeRender' in $$props) $$invalidate(14, jobsBeforeRender = $$props.jobsBeforeRender);
		if ('$$scope' in $$props) $$invalidate(18, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, rowSelectionStore*/ 131328) {
			$: if (__mounted) setProp('rowSelectionStore', rowSelectionStore);
		}

		if ($$self.$$.dirty & /*__mounted, viewportRow*/ 131584) {
			$: if (__mounted) setProp('viewportRow', viewportRow);
		}

		if ($$self.$$.dirty & /*__mounted, viewportCol*/ 132096) {
			$: if (__mounted) setProp('viewportCol', viewportCol);
		}

		if ($$self.$$.dirty & /*__mounted, dimensionRow*/ 133120) {
			$: if (__mounted) setProp('dimensionRow', dimensionRow);
		}

		if ($$self.$$.dirty & /*__mounted, colData*/ 135168) {
			$: if (__mounted) setProp('colData', colData);
		}

		if ($$self.$$.dirty & /*__mounted, dataStore*/ 139264) {
			$: if (__mounted) setProp('dataStore', dataStore);
		}

		if ($$self.$$.dirty & /*__mounted, jobsBeforeRender*/ 147456) {
			$: if (__mounted) setProp('jobsBeforeRender', jobsBeforeRender);
		}
	};

	return [
		readonly,
		range,
		rowClass,
		additionalData,
		type,
		colType,
		__ref,
		onEvent,
		rowSelectionStore,
		viewportRow,
		viewportCol,
		dimensionRow,
		colData,
		dataStore,
		jobsBeforeRender,
		updateCell,
		getWebComponent,
		__mounted,
		$$scope,
		slots,
		revogr_data_binding
	];
}

class RevogrData extends SvelteComponent {
  $$prop_def: RevogrDataProps;
  $$events_def: RevogrDataEvents;
  $$slot_def: RevogrDataSlots;

  $on<K extends keyof RevogrDataEvents>(type: K, callback: (e: RevogrDataEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<RevogrDataProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			readonly: 0,
			range: 1,
			rowClass: 2,
			additionalData: 3,
			rowSelectionStore: 8,
			viewportRow: 9,
			viewportCol: 10,
			dimensionRow: 11,
			colData: 12,
			dataStore: 13,
			type: 4,
			colType: 5,
			jobsBeforeRender: 14,
			updateCell: 15,
			getWebComponent: 16
		});
	}

	
  /** Pointed cell update. */
 get updateCell(): Components.RevogrData["updateCell"] {
		return this.$$.ctx[15];
	}

	get getWebComponent(): HTMLRevogrDataElement | undefined {
		return this.$$.ctx[16];
	}
}

export default RevogrData;