/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@revolist/revogrid';


interface RevogrHeaderProps {
  
  /** Viewport X */
  viewportCol?: Components.RevogrHeader["viewportCol"]
  
  /** Dimension settings X */
  dimensionCol?: Components.RevogrHeader["dimensionCol"]
  
  /** Selection, range, focus */
  selectionStore?: Components.RevogrHeader["selectionStore"]
  
  /** Column groups */
  groups?: Components.RevogrHeader["groups"]
  
  /** Grouping depth, how many levels of grouping */
  groupingDepth?: Components.RevogrHeader["groupingDepth"]
  
  /** Readonly mode */
  readonly?: Components.RevogrHeader["readonly"]
  
  /** If columns can be resized */
  canResize?: Components.RevogrHeader["canResize"]
  
  /** Defines resize position */
  resizeHandler?: Components.RevogrHeader["resizeHandler"]
  
  /** Columns - defines an array of grid columns. */
  colData?: Components.RevogrHeader["colData"]
  
  /** Column filter */
  columnFilter?: Components.RevogrHeader["columnFilter"]
  
  /** Column type */
  type?: Components.RevogrHeader["type"]
  
  /** Extra properties to pass into header renderer, such as vue or react components to handle parent */
  additionalData?: Components.RevogrHeader["additionalData"]
}

interface RevogrHeaderEvents {
  
  /** On initial header click */
  beforeheaderclick: Parameters<JSX.RevogrHeader["onBeforeheaderclick"]>[0]
  
  /** On header resize */
  headerresize: Parameters<JSX.RevogrHeader["onHeaderresize"]>[0]
  
  /** On before header resize */
  beforeheaderresize: Parameters<JSX.RevogrHeader["onBeforeheaderresize"]>[0]
  
  /** On header double click */
  headerdblclick: Parameters<JSX.RevogrHeader["onHeaderdblclick"]>[0]
}

interface RevogrHeaderSlots {
  default: any
}
  
/* generated by Svelte v4.2.18 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	listen,
	run_all,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import "svelte/internal/disclose-version";
import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let revogr_header;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[17].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[16], null);

	return {
		c() {
			revogr_header = element("revogr-header");
			if (default_slot) default_slot.c();
			set_custom_element_data(revogr_header, "grouping-depth", /*groupingDepth*/ ctx[0]);
			set_custom_element_data(revogr_header, "readonly", /*readonly*/ ctx[1]);
			set_custom_element_data(revogr_header, "can-resize", /*canResize*/ ctx[2]);
			set_custom_element_data(revogr_header, "column-filter", /*columnFilter*/ ctx[3]);
			set_custom_element_data(revogr_header, "type", /*type*/ ctx[4]);
			set_custom_element_data(revogr_header, "additional-data", /*additionalData*/ ctx[5]);
		},
		m(target, anchor) {
			insert(target, revogr_header, anchor);

			if (default_slot) {
				default_slot.m(revogr_header, null);
			}

			/*revogr_header_binding*/ ctx[18](revogr_header);
			current = true;

			if (!mounted) {
				dispose = [
					listen(revogr_header, "beforeheaderclick", /*onEvent*/ ctx[7]),
					listen(revogr_header, "headerresize", /*onEvent*/ ctx[7]),
					listen(revogr_header, "beforeheaderresize", /*onEvent*/ ctx[7]),
					listen(revogr_header, "headerdblclick", /*onEvent*/ ctx[7])
				];

				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 65536)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[16],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[16])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[16], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*groupingDepth*/ 1) {
				set_custom_element_data(revogr_header, "grouping-depth", /*groupingDepth*/ ctx[0]);
			}

			if (!current || dirty & /*readonly*/ 2) {
				set_custom_element_data(revogr_header, "readonly", /*readonly*/ ctx[1]);
			}

			if (!current || dirty & /*canResize*/ 4) {
				set_custom_element_data(revogr_header, "can-resize", /*canResize*/ ctx[2]);
			}

			if (!current || dirty & /*columnFilter*/ 8) {
				set_custom_element_data(revogr_header, "column-filter", /*columnFilter*/ ctx[3]);
			}

			if (!current || dirty & /*type*/ 16) {
				set_custom_element_data(revogr_header, "type", /*type*/ ctx[4]);
			}

			if (!current || dirty & /*additionalData*/ 32) {
				set_custom_element_data(revogr_header, "additional-data", /*additionalData*/ ctx[5]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) {
				detach(revogr_header);
			}

			if (default_slot) default_slot.d(detaching);
			/*revogr_header_binding*/ ctx[18](null);
			mounted = false;
			run_all(dispose);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { viewportCol = undefined } = $$props;
	let { dimensionCol = undefined } = $$props;
	let { selectionStore = undefined } = $$props;
	let { groups = undefined } = $$props;
	let { groupingDepth = undefined } = $$props;
	let { readonly = undefined } = $$props;
	let { canResize = undefined } = $$props;
	let { resizeHandler = undefined } = $$props;
	let { colData = undefined } = $$props;
	let { columnFilter = undefined } = $$props;
	let { type } = $$props;
	let { additionalData = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(15, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(6, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function revogr_header_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(6, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('viewportCol' in $$props) $$invalidate(8, viewportCol = $$props.viewportCol);
		if ('dimensionCol' in $$props) $$invalidate(9, dimensionCol = $$props.dimensionCol);
		if ('selectionStore' in $$props) $$invalidate(10, selectionStore = $$props.selectionStore);
		if ('groups' in $$props) $$invalidate(11, groups = $$props.groups);
		if ('groupingDepth' in $$props) $$invalidate(0, groupingDepth = $$props.groupingDepth);
		if ('readonly' in $$props) $$invalidate(1, readonly = $$props.readonly);
		if ('canResize' in $$props) $$invalidate(2, canResize = $$props.canResize);
		if ('resizeHandler' in $$props) $$invalidate(12, resizeHandler = $$props.resizeHandler);
		if ('colData' in $$props) $$invalidate(13, colData = $$props.colData);
		if ('columnFilter' in $$props) $$invalidate(3, columnFilter = $$props.columnFilter);
		if ('type' in $$props) $$invalidate(4, type = $$props.type);
		if ('additionalData' in $$props) $$invalidate(5, additionalData = $$props.additionalData);
		if ('$$scope' in $$props) $$invalidate(16, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, viewportCol*/ 33024) {
			$: if (__mounted) setProp('viewportCol', viewportCol);
		}

		if ($$self.$$.dirty & /*__mounted, dimensionCol*/ 33280) {
			$: if (__mounted) setProp('dimensionCol', dimensionCol);
		}

		if ($$self.$$.dirty & /*__mounted, selectionStore*/ 33792) {
			$: if (__mounted) setProp('selectionStore', selectionStore);
		}

		if ($$self.$$.dirty & /*__mounted, groups*/ 34816) {
			$: if (__mounted) setProp('groups', groups);
		}

		if ($$self.$$.dirty & /*__mounted, resizeHandler*/ 36864) {
			$: if (__mounted) setProp('resizeHandler', resizeHandler);
		}

		if ($$self.$$.dirty & /*__mounted, colData*/ 40960) {
			$: if (__mounted) setProp('colData', colData);
		}
	};

	return [
		groupingDepth,
		readonly,
		canResize,
		columnFilter,
		type,
		additionalData,
		__ref,
		onEvent,
		viewportCol,
		dimensionCol,
		selectionStore,
		groups,
		resizeHandler,
		colData,
		getWebComponent,
		__mounted,
		$$scope,
		slots,
		revogr_header_binding
	];
}

class RevogrHeader extends SvelteComponent {
  $$prop_def: RevogrHeaderProps;
  $$events_def: RevogrHeaderEvents;
  $$slot_def: RevogrHeaderSlots;

  $on<K extends keyof RevogrHeaderEvents>(type: K, callback: (e: RevogrHeaderEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<RevogrHeaderProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			viewportCol: 8,
			dimensionCol: 9,
			selectionStore: 10,
			groups: 11,
			groupingDepth: 0,
			readonly: 1,
			canResize: 2,
			resizeHandler: 12,
			colData: 13,
			columnFilter: 3,
			type: 4,
			additionalData: 5,
			getWebComponent: 14
		});
	}

	get getWebComponent(): HTMLRevogrHeaderElement | undefined {
		return this.$$.ctx[14];
	}
}

export default RevogrHeader;